export const animeData = [
  {
    id: 1,
    title: "Assassination Classroom Season 1",
    youtube: "https://youtu.be/kgNkGohA20k?si=KS6p5fs4XPHqbreU",
    animeyear: 2015,
    animeduration: 24,
    season: 1,
    episodes: 22,
    imdbRating: 8.3,
    description:
      "A classroom of students must kill their alien teacher to save the world.",
    imageUrl: "https://i.postimg.cc/vBJmH649/images.jpg",
    animeUrl: "/naruto",
    genres: ["Action", "Comedy", "School", "Shounen"],
    ep1: "https://www.youtube.com/watch?v=kgNkGohA20k",
    ep2: "https://www.youtube.com/watch?v=kgNkGohA20k",
    ep3: "https://www.youtube.com/watch?v=kgNkGohA20k",
  },
  {
    id: 2,
    title: "Alya Sometimes Hides Her Feelings in Russian",
    animeyear: 2024,
    animeduration: 24,
    youtube: "https://www.youtube.com/watch?v=uLENIok9Dr8",
    season: 1,
    episodes: 12,
    imdbRating: 7.1,
    description:
      "A story about a girl hiding her feelings and navigating relationships.",
    imageUrl:
      "https://i.postimg.cc/9FmvSM5J/MV5-BNjg0-YTVj-NTIt-ZTI1-ZC00-MDZl-LTll-Yj-Qt-MDY0-ODMx-NDdl-Yj-Y3-Xk-Ey-Xk-Fqc-Gc-V1-FMjpg-UX1000.jpg",
    animeUrl: "/",
    genres: ["Romance", "Slice of Life", "Drama"],
  },
  {
    id: 3,
    title: "Assassination Classroom Season 2",
    animeyear: 2016,
    animeduration: 24,
    season: 2,
    episodes: 25,
    imdbRating: 8.7,
    description:
      "The students continue their mission to kill their teacher as time runs out.",
    imageUrl:
      "https://i.postimg.cc/8z6Bm2PN/o-Te-MBICUAL2d-JVd-B11-B45y-TCGg5.jpg",
    animeUrl: "/",
    genres: ["Action", "Comedy", "School", "Shounen"],
  },
  {
    id: 4,
    title: "Bye Bye, Earth",
    animeyear: 2024,
    animeduration: 24,
    season: 1,
    episodes: 12,
    imdbRating: 6.9,
    description: "A sci-fi anime set in a post-apocalyptic world.",
    imageUrl: "https://i.postimg.cc/qRfFGcdZ/bye-bye-earth.jpg",
    animeUrl: "/",
    genres: ["Sci-Fi", "Drama", "Action"],
  },
  {
    id: 5,
    title: "Days with My Stepsister Season 1",
    isWishlistExclusive: false,
    animeyear: 2024,
    animeduration: 24,
    season: 1,
    episodes: 12,
    imdbRating: 7.0,
    description:
      "A story about the challenges of living with a new stepsister.",
    imageUrl:
      "https://i.postimg.cc/43Nw5KDT/MV5-BZDU2-MWNi-YWMt-Mj-Ix-ZS00-ZTVl-LTkx-ZDAt-Yz-A5-Yz-Fh-ODBh-ODAy-Xk-Ey-Xk-Fqc-Gc-V1-FMjpg-UX1000.jpg",
    animeUrl: "/",
    genres: ["Romance", "Comedy", "Slice of Life"],
  },
  {
    id: 6,
    title: "Dr. STONE Season 2",
    isWishlistExclusive: false,
    animeyear: 2021,
    animeduration: 24,
    season: 2,
    episodes: 11,
    imdbRating: 8.4,
    description:
      "A post-apocalyptic world where science helps humanity rebuild.",
    imageUrl: "https://i.postimg.cc/8CT4kyNG/OIP-2.jpg",
    animeUrl: "/",
    genres: ["Action", "Adventure", "Sci-Fi", "Shounen"],
  },
  {
    id: 7,
    title: "Fairy Tail: 100 Years Quest",
    isWishlistExclusive: false,
    animeyear: 2024,
    animeduration: 24,
    season: 1,
    episodes: 12,
    imdbRating: 7.8,
    description:
      "The next chapter in the Fairy Tail guild's legendary adventures.",
    imageUrl:
      "https://i.postimg.cc/Mpm0LyRF/4453c15bb8b93115a72886112afbe087247318588beaf0e46539aa55a9bb28a7-RI-TTW.jpg",
    animeUrl: "/",
    genres: ["Action", "Adventure", "Fantasy", "Shounen"],
  },
  {
    id: 8,
    title: "Haikyu!! Season 1",
    isWishlistExclusive: false,
    animeyear: 2014,
    animeduration: 24,
    season: 1,
    episodes: 25,
    imdbRating: 8.7,
    description: "A high school volleyball team's journey to the top.",
    imageUrl:
      "https://i.postimg.cc/02gBR0Mk/1-Rfa9o5-H6-Zl-Xzb-DVNlw4j-ULd-Xpi.jpg",
    animeUrl: "/",
    genres: ["Sports", "Shounen", "Drama", "School"],
  },
  {
    id: 9,
    title: "Kaiju No. 8 Season 1",
    isWishlistExclusive: false,
    animeyear: 2024,
    animeduration: 24,
    season: 1,
    episodes: 12,
    imdbRating: 8.2,
    description: "A man who transforms into a kaiju must fight other kaiju.",
    imageUrl:
      "https://i.postimg.cc/q7RThxGf/c1-T8-UHw-Caq6-Je-QYgt4-U8-ERPGox-N.jpg",
    animeUrl: "/kai",
    genres: ["Action", "Sci-Fi", "Fantasy", "Shounen"],
  },
  {
    id: 10,
    title: "Log Horizon Season 1",
    isWishlistExclusive: false,
    animeyear: 2013,
    animeduration: 25,
    season: 1,
    episodes: 25,
    imdbRating: 7.9,
    description: "Players of a virtual MMORPG must adapt to their new world.",
    imageUrl:
      "https://i.postimg.cc/SRMJbrMb/x-LGd-Ru-WCn2-Al-By-L5-Y9-OLB3-Zw-Itg.jpg",
    animeUrl: "/",
    genres: ["Adventure", "Fantasy", "Game", "Shounen"],
  },
  {
    id: 11,
    title: "Makeine: Too Many Losing Heroines!",
    isWishlistExclusive: false,
    animeyear: 2024,
    animeduration: 24,
    season: 1,
    episodes: 12,
    imdbRating: 6.8,
    description:
      "A story about a protagonist surrounded by multiple romantic interests.",
    imageUrl: "https://i.postimg.cc/wjT05fRB/OIP-1.jpg",
    animeUrl: "/",
    genres: ["Romance", "Comedy", "Harem", "Slice of Life"],
  },
  {
    id: 12,
    title: "No Longer Allowed in Another World Season 1",
    isWishlistExclusive: false,
    animeyear: 2024,
    animeduration: 24,
    season: 1,
    episodes: 12,
    imdbRating: 6.5,
    description:
      "A person is banished from a fantasy world and faces consequences.",
    imageUrl: "https://i.postimg.cc/cH5nSCkw/season-1.jpg",
    animeUrl: "/",
    genres: ["Adventure", "Fantasy", "Action", "Isekai"],
  },
  {
    id: 13,
    title: "Quality Assurance in Another World",
    isWishlistExclusive: false,
    animeyear: 2024,
    animeduration: 24,
    season: 1,
    episodes: 12,
    imdbRating: 7.0,
    description:
      "An office worker is transported to a fantasy world with the task of ensuring its quality.",
    imageUrl:
      "https://i.postimg.cc/pTxZTsvx/anime-quality-assurance-in-another-world-visuel-2.avif",
    animeUrl: "/",
    genres: ["Comedy", "Fantasy", "Isekai", "Slice of Life"],
  },
  {
    id: 14,
    title: "Solo Leveling Season 1",
    isWishlistExclusive: false,
    animeyear: 2024,
    animeduration: 24,
    season: 1,
    episodes: 12,
    imdbRating: 8.9,
    description:
      "A weak hunter gains extraordinary power and levels up in a dangerous world.",
    imageUrl:
      "https://i.postimg.cc/MZs116wh/75c-ENUBSmn-ON8-IBDc2-F979-CMus-N.jpg",
    animeUrl: "/",
    genres: ["Action", "Fantasy", "Adventure", "Shounen"],
  },
  {
    id: 15,
    title:
      "The Strongest Magician in the Demon Lord's Army Was a Human Season 1",
    isWishlistExclusive: false,
    animeyear: 2024,
    animeduration: 24,
    season: 1,
    episodes: 12,
    imdbRating: 7.2,
    description:
      "A human becomes the strongest magician in a demon lord's army.",
    imageUrl: "https://i.postimg.cc/cJf7xb1X/maougun-KV-1452x2048.png",
    animeUrl: "/",
    genres: ["Action", "Fantasy", "Adventure", "Isekai"],
  },
  {
    id: 16,
    title: "Tower of God Season 2",
    isWishlistExclusive: false,
    animeyear: 2024,
    animeduration: 24,
    season: 2,
    episodes: 12,
    imdbRating: 8.1,
    description:
      "The quest to reach the top of the Tower continues with new challenges.",
    imageUrl: "https://i.postimg.cc/8Cm9kJvF/og-image.webp",
    animeUrl: "/",
    genres: ["Action", "Adventure", "Fantasy", "Shounen"],
  },
  {
    id: 17,
    title: "True Beauty Season 1",
    isWishlistExclusive: false,
    animeyear: 2024,
    animeduration: 24,
    season: 1,
    episodes: 12,
    imdbRating: 7.5,
    description: "A beauty makeover changes a girl's life and relationships.",
    imageUrl: "https://i.postimg.cc/mDKWRkmv/true-beauty-snwt-960.webp",
    animeUrl: "/",
    genres: ["Romance", "Comedy", "Drama", "Slice of Life"],
  },
  {
    id: 18,
    title: "Twilight Out of Focus Season 1",
    isWishlistExclusive: false,
    animeyear: 2024,
    animeduration: 24,
    season: 1,
    episodes: 12,
    imdbRating: 7.3,
    description:
      "A romance drama with unique perspectives and intense emotions.",
    imageUrl:
      "https://i.postimg.cc/dtV554Wf/MV5-BOTZh-ZWQ3-ZGUt-Zj-M2-NC00-OTVi-LWI3-Mz-It-OWJk-Nz-Fk-Y2-Zh-Mzcw-Xk-Ey-Xk-Fqc-Gc-V1-FMjpg-UX1000.jpg",
    animeUrl: "/",
    genres: ["Romance", "Drama", "Slice of Life"],
  },
  {
    id: 19,
    title: "Viral Hit Season 1",
    isWishlistExclusive: false,
    animeyear: 2024,
    animeduration: 24,
    season: 1,
    episodes: 12,
    imdbRating: 7.6,
    description: "A boy navigates the chaotic world of viral stardom.",
    imageUrl: "https://i.postimg.cc/dQgzQKXK/1284207.jpg",
    animeUrl: "/",
    genres: ["Comedy", "Drama", "Slice of Life"],
  },
  {
    id: 20,
    title:
      "VTuber Legend: How I Went Viral After Forgetting to Turn Off My Stream",
    isWishlistExclusive: false,
    animeyear: 2024,
    animeduration: 24,
    season: 1,
    episodes: 12,
    imdbRating: 6.9,
    description: "A VTuber's rise to fame in an unexpected way.",
    imageUrl: "https://i.postimg.cc/t42FX9Tq/OIP.jpg",
    animeUrl: "/",
    genres: ["Comedy", "Drama", "Slice of Life"],
  },
  {
    id: 21,
    title: "Why Does Nobody Remember Me In This World",
    isWishlistExclusive: false,
    animeyear: 2024,
    animeduration: 24,
    season: 1,
    episodes: 12,
    imdbRating: 7.0,
    description: "A person is forgotten in a world where memories are the key.",
    imageUrl: "https://i.postimg.cc/DZDtRVs5/season-1-1.jpg",
    animeUrl: "/",
    genres: ["Fantasy", "Mystery", "Drama", "Isekai"],
  },
  {
    id: 22,
    title: "Wistoria: Wand and Sword",
    isWishlistExclusive: false,
    animeyear: 2024,
    animeduration: 24,
    season: 1,
    episodes: 12,
    imdbRating: 7.4,
    description:
      "A magical adventure involving wands and swords in a fantasy world.",
    imageUrl:
      "https://i.postimg.cc/1tHQd7Bj/5n0-IZQA9-Mi-Xn5-JBKZibt-Nhh-FSAZ.jpg",
    animeUrl: "/",
    genres: ["Action", "Fantasy", "Adventure"],
  },
  {
    id: 23,
    title: "Demon Slayer Season 2",
    isWishlistExclusive: false,
    animeyear: 2021,
    animeduration: 24,
    season: 2,
    episodes: 18,
    imdbRating: 9.0,
    description: "The next phase of Tanjiro's journey in the world of demons.",
    imageUrl: "https://images.justwatch.com/poster/256743734/s718/season-2.jpg",
    animeUrl: "/",
    genres: ["Action", "Adventure", "Fantasy", "Shounen"],
  },
  {
    id: 24,
    title: "Horimiya: The Missing Pieces Premiered",
    isWishlistExclusive: false,
    animeyear: 2023,
    animeduration: 24,
    season: 1,
    episodes: 13,
    imdbRating: 8.2,
    description: "The untold stories and extra chapters of the Horimiya manga.",
    imageUrl:
      "https://i.postimg.cc/zX257gjr/a-EJVHb-Xa-C94y6th-J3n-A6l-BBn-Hjs.jpg",
    animeUrl: "/",
    genres: ["Romance", "Comedy", "Slice of Life"],
  },
  {
    id: 25,
    title: "Jujutsu Kaisen Season 2",
    isWishlistExclusive: false,
    animeyear: 2023,
    animeduration: 24,
    season: 2,
    episodes: 23,
    imdbRating: 9.1,
    description:
      "The battle against curses continues in Jujutsu Kaisen Season 2.",
    imageUrl:
      "https://a.storyblok.com/f/178900/2000x3000/8863dbd7c8/jujutsu-kaisen-season-2-key-art.png/m/filters:quality(95)format(webp)",
    animeUrl: "/",
    genres: ["Action", "Supernatural", "Shounen", "Fantasy"],
  },
  {
    id: 26,
    title: "Jujutsu Kaisen Season 1",
    isWishlistExclusive: false,
    animeyear: 2020,
    animeduration: 24,
    season: 1,
    episodes: 24,
    imdbRating: 8.8,
    description:
      "A high school student becomes involved in the world of Jujutsu Sorcerers.",
    imageUrl:
      "https://i.postimg.cc/QCHTNWmg/MV5-BNGY4-MTg3-Nzgt-Mm-Fk-Zi00-NTg5-LWEx-Mm-Et-MWI3-Yz-I1-ODdm-MWQ1-Xk-Ey-Xk-Fqc-Gde-QXVy-Mj-Qw-MDg0-Ng-V1-FMjpg-UX1000.jpg",
    animeUrl: "/",
    genres: ["Action", "Supernatural", "Shounen", "Fantasy"],
  },
  {
    id: 27,
    title: "Spy x Family Season 2",
    isWishlistExclusive: false,
    animeyear: 2023,
    animeduration: 24,
    season: 2,
    episodes: 12,
    imdbRating: 8.7,
    description:
      "The Forger family continues to navigate the world of spies, assassins, and secrets.",
    imageUrl:
      "https://image.tmdb.org/t/p/original/f4PmYfliarqfMeFNdnK6NZ6AU5i.jpg",
    animeUrl: "/",
    genres: ["Action", "Comedy", "Slice of Life", "Spy"],
  },
  {
    id: 28,
    title: "Mushoku Tensei: Jobless Reincarnation",
    isWishlistExclusive: false,
    animeyear: 2021,
    animeduration: 24,
    season: 2,
    episodes: 23,
    imdbRating: 8.5,
    description:
      "A jobless man gets reincarnated in a fantasy world and decides to live a meaningful life.",
    imageUrl: "https://i.postimg.cc/DyfSpxxH/image.jpg",
    animeUrl: "/",
    genres: ["Fantasy", "Adventure", "Isekai", "Drama"],
  },
  {
    id: 29,
    title: "Demon Slayer Season 3",
    isWishlistExclusive: false,
    animeyear: 2023,
    animeduration: 24,
    season: 3,
    episodes: 11,
    imdbRating: 9.2,
    description:
      "Tanjiro's journey continues as he faces new challenges in the fight against demons.",
    imageUrl: "https://i.postimg.cc/SNtxTk2Y/64490a8ddaabca001da8fe61.jpg",
    animeUrl: "/",
    genres: ["Action", "Adventure", "Fantasy", "Shounen"],
  },
  {
    id: 30,
    title: "Demon Slayer Season 4",
    isWishlistExclusive: false,
    animeyear: 2024,
    animeduration: 24,
    season: 4,
    episodes: 12,
    imdbRating: 9.3,
    description:
      "A new season of Tanjiro's demon-slaying adventures unfolds with even stronger enemies.",
    imageUrl:
      "https://i.postimg.cc/tC7XVwSq/demon-slayer-s4-poster-1714500560283.jpg",
    animeUrl: "/",
    genres: ["Action", "Adventure", "Fantasy", "Shounen"],
  },
  {
    id: 31,
    title: "An Archdemon's Dilemma: How to Love Your Elf Bride Season 1",
    isWishlistExclusive: true,
    animeyear: 2024,
    animeduration: 24,
    season: 1,
    episodes: 12,
    imdbRating: 7.1,
    description:
      "An archdemon struggles with how to express love for his elf bride in this fantasy story.",
    imageUrl:
      "https://i.postimg.cc/GmydXYn6/MV5-BOWVi-Nm-M5-Yj-Yt-NWJl-Yi00-MDk4-LWE1-MTIt-MTg2-N2-Q4-ODRk-YTU2-Xk-Ey-Xk-Fqc-Gde-QXVy-Mzgx-ODM4-Nj-M-V1.jpg",
    animeUrl: "/",
    genres: ["Romance", "Fantasy", "Comedy", "Isekai"],
  },
  {
    id: 32,
    title: "Mashle: Magic and Muscles Season 2",
    isWishlistExclusive: false,
    animeyear: 2024,
    animeduration: 24,
    episodes: 12,
    imdbRating: 7.9,
    description:
      "Mash Burnedead continues his magical training, fighting against enemies with his muscles.",
    imageUrl:
      "https://a.storyblok.com/f/178900/849x1200/3ea3addb7a/mashle-s2-kv.jpeg/m/filters:quality(95)format(webp)",
    animeUrl: "/",
    genres: ["Action", "Comedy", "Fantasy", "Shounen"],
  },
  {
    id: 33,
    title: "Naruto Season 1",
    isWishlistExclusive: false,
    animeyear: 2002,
    animeduration: 24,
    episodes: 57,
    imdbRating: 8.4,
    description:
      "Naruto Uzumaki embarks on his journey to become a Hokage, facing trials along the way.",
    imageUrl: "https://i.postimg.cc/nzgtKcwn/images.jpg",
    animeUrl: "/",
    genres: ["Action", "Adventure", "Shounen", "Ninja"],
  },
  {
    id: 34,
    title: "Wind Breaker Season 1",
    isWishlistExclusive: false,
    animeyear: 2024,
    animeduration: 24,
    episodes: 12,
    imdbRating: 7.8,
    description:
      "A story about a boy who becomes part of a cycling team and fights against various challenges.",
    imageUrl:
      "https://i.postimg.cc/TY9QDNsP/MV5-BNTQz-NDI5-OGIt-ZDZk-My00-MWQ1-LWIw-M2-Yt-Yzc2-YWNh-OGJl-ZWQx-Xk-Ey-Xk-Fqc-Gc-V1-FMjpg-UX1000.jpg",
    animeUrl: "/",
    genres: ["Sports", "Action", "Drama", "Shounen"],
  },
  {
    id: 35,
    title: "Ranking of Kings Season 1",
    isWishlistExclusive: false,
    animeyear: 2021,
    animeduration: 24,
    episodes: 23,
    imdbRating: 8.6,
    description:
      "A young prince who is deaf and mute embarks on a journey to prove his worth to the kingdom.",
    imageUrl:
      "https://i.postimg.cc/JnVjgjFg/MV5-BNj-M3-OWRm-ODQt-ODVj-YS00-Yz-Y5-LWFi-Nm-Qt-OGEx-M2-M4-OWQ3-Nzk1-Xk-Ey-Xk-Fqc-Gc-V1-FMjpg-UX1000.jpg",
    animeUrl: "/",
    genres: ["Adventure", "Fantasy", "Drama", "Shounen"],
  },
  {
    id: 36,
    title: "Akebi's Sailor Uniform Season 1",
    isWishlistExclusive: false,
    animeyear: 2022,
    animeduration: 24,
    episodes: 12,
    imdbRating: 7.3,
    description:
      "A girl wearing a sailor uniform navigates school life and friendships.",
    imageUrl:
      "https://i.postimg.cc/FRCNzxQC/MV5-BMWRk-NWE1-M2-Ut-ZTAz-OC00-ZTI0-LTll-Mzkt-ZTA0-ZTRi-Mjdj-Nm-Y5-Xk-Ey-Xk-Fqc-Gde-QXVy-Mzgx-ODM4-Nj-M-V1-FMjpg-UX1000.jpg",
    animeUrl: "/",
    genres: ["Slice of Life", "School", "Comedy", "Drama"],
  },
  {
    id: 37,
    title: "Black Rock Shooter: Dawn Fall Season 1",
    isWishlistExclusive: false,
    animeyear: 2022,
    animeduration: 24,
    episodes: 12,
    imdbRating: 6.7,
    description:
      "A supernatural anime about the bond between two girls and their battles in an alternate world.",
    imageUrl: "https://i.postimg.cc/C15p3ffG/images-1.jpg",
    animeUrl: "/",
    genres: ["Action", "Supernatural", "Drama", "Fantasy"],
  },
  {
    id: 38,
    title: "One Punch Man Season 1",
    isWishlistExclusive: false,
    animeyear: 2015,
    animeduration: 24,
    episodes: 12,
    imdbRating: 8.7,
    description:
      "A superhero who defeats any opponent with a single punch searches for a real challenge.",
    imageUrl:
      "https://i.postimg.cc/qqnJFC9m/MV5-BZj-Jl-Nz-E5-Yz-Et-Yz-Qw-YS00-NTBj-LTk5-Yz-At-Yz-Uw-OWQy-M2-E3-OGI2-Xk-Ey-Xk-Fqc-Gde-QXVy-NTgy-NTA4-Mj-M-V1-FMjpg-UX1000.jpg",
    animeUrl: "/",
    genres: ["Action", "Comedy", "Superhero", "Shounen"],
  },
  {
    id: 39,
    title: "Chainsaw Man Season 1",
    isWishlistExclusive: false,
    animeyear: 2022,
    animeduration: 24,
    episodes: 12,
    imdbRating: 8.8,
    description:
      "A boy becomes a chainsaw-wielding demon hunter after making a contract with a devil.",
    imageUrl: "https://i.postimg.cc/vBHvQSkp/Chainsawman-2.jpg",
    animeUrl: "/",
    genres: ["Action", "Supernatural", "Shounen", "Horror"],
  },
  {
    id: 40,
    title: "I Got a Cheat Skill in Another World",
    isWishlistExclusive: false,
    animeyear: 2023,
    animeduration: 24,
    episodes: 12,
    imdbRating: 7.0,
    description:
      "A young man finds himself in a world where his cheat skills give him an advantage in the new world.",
    imageUrl:
      "https://i.postimg.cc/tRNqxv1s/MV5-BZDBj-Zj-Q1-ZWQt-NWJl-MS00-MWFi-LWE0-NDAt-NDhi-Mzk0-MTZm-M2-Vi-Xk-Ey-Xk-Fqc-Gde-QXVy-Mzgx-ODM4-Nj-M-V1-FMjpg-UX1000.jpg",
    animeUrl: "/",
    genres: ["Fantasy", "Action", "Isekai", "Adventure"],
  },
  {
    id: 41,
    title: "BLUELOCK Season 1",
    isWishlistExclusive: false,
    animeyear: 2022,
    animeduration: 24,
    episodes: 24,
    imdbRating: 8.3,
    description:
      "A soccer competition to find the most talented striker in Japan begins.",
    imageUrl: "https://i.postimg.cc/YqsjCj7C/E85-Ab-Dw-Vg-AQV5-AV.jpg",
    animeUrl: "/",
    genres: ["Sports", "Action", "Shounen"],
  },
  {
    id: "one-piece",
    title: "DanDaDan Season 1",
    isWishlistExclusive: false,
    animeyear: 2024,
    animeduration: 24,
    episodes: 12,
    imdbRating: 8.1,
    description:
      "A thrilling and supernatural adventure that follows two characters' journey into strange situations.",
    imageUrl:
      "https://m.media-amazon.com/images/M/MV5BYWFhOWMxNTYtZThiMi00ZmQ5LTlmODktN2QwNzUyZjMyZGQzXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    animeUrl: "/",
    genres: ["Action", "Comedy", "Supernatural", "Shounen"],
  },

  {
    id: "one-piece2",
    title: "One Piece",
    isWishlistExclusive: true,
    description: "A young pirate's quest to find the ultimate treasure.",
    imageUrl:
      "https://dthezntil550i.cloudfront.net/oa/latest/oa2110022253540810022121500/1280_960/9f49711a-be42-4ade-926c-b5d96bfa2a25.png",
    animeUrl: "https://example.com/naruto",
  },
];
